export type Recipe = {
  slug: string
  name: string
  description: string
  baseSpirit: 'rum' | 'bourbon' | 'liqueur' | 'tequila'
  image: string
  ingredients: string[]
  instructions: string[]
  difficulty: 'Easy' | 'Medium' | 'Advanced'
  prepTime: string
  taste: string
  category: string
}

export const recipes: Recipe[] = [
  // Existing recipes
  {
    slug: 'rum-punch',
    name: 'Rum Punch',
    description: 'A tropical classic featuring Ponce Rum with citrus and spice.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/cocktail-rum-punch.jpg',
    ingredients: ['2oz Ponce Rum', '1oz Lime Juice', '1oz Simple Syrup', 'Dash Angostura'],
    instructions: [
      'Fill a shaker with ice.',
      'Add Ponce Rum, lime juice, simple syrup, and Angostura bitters.',
      'Shake vigorously for 10-15 seconds.',
      'Strain into a rocks glass filled with fresh ice.',
      'Garnish with a lime wheel and enjoy.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Tropical',
  },
  {
    slug: 'bourbon-sour',
    name: 'Bourbon Sour',
    description: 'A smooth, frothy classic showcasing Florida Bourbon with maple sweetness.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/cocktail-bourbon-sour.jpg',
    ingredients: ['2oz Florida Bourbon', '0.75oz Lemon', '0.5oz Maple Syrup', 'Egg White'],
    instructions: [
      'Add bourbon, lemon juice, maple syrup, and egg white to a shaker without ice.',
      'Dry shake vigorously for 15 seconds to emulsify the egg white.',
      'Add ice to the shaker and shake again for another 10 seconds.',
      'Strain into a chilled coupe or rocks glass.',
      'Garnish with a lemon twist or cherry.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Classic',
  },
  {
    slug: 'paan-martini',
    name: 'Paan Martini',
    description: 'An exotic twist on the classic martini featuring aromatic Paan Liqueur.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/cocktail-paan-martini.jpg',
    ingredients: ['1.5oz Paan Liqueur', '1oz Vodka', 'Splash of Cream'],
    instructions: [
      'Fill a mixing glass with ice.',
      'Add Paan Liqueur, vodka, and cream.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a chilled martini glass.',
      'Garnish with a betel leaf or rose petal.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Rich',
    category: 'Sophisticated',
  },
  {
    slug: 'tequila-sunrise',
    name: 'Tequila Sunrise',
    description: 'A vibrant Florida sunset in a glass with Tikaram Tequila.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-sunrise.webp',
    ingredients: ['2oz Tikaram Tequila', 'Orange Juice', 'Grenadine'],
    instructions: [
      'Fill a highball glass with ice.',
      'Pour Tikaram Tequila over the ice.',
      'Top with orange juice, leaving about an inch at the top.',
      'Slowly pour grenadine over the back of a spoon to create a layered effect.',
      'Garnish with an orange slice and cherry.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Sweet',
    category: 'Classic',
  },
  // Bourbon recipes
  {
    slug: 'bourbon-distillers-coffee',
    name: 'Bourbon Distillers Coffee',
    description: 'A rich Florida twist on Irish coffee featuring smooth Florida Bourbon with coffee and cream.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-distillers-coffee.webp',
    ingredients: ['2oz Florida Bourbon', 'Hot Coffee', '0.5oz Simple Syrup', 'Heavy Cream'],
    instructions: [
      'Pour Florida Bourbon and simple syrup into a warm mug, then fill with hot coffee.',
      'Gently float heavy cream over the back of a spoon on top.',
      'Garnish with coffee beans and serve immediately.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Rich',
    category: 'Classic',
  },
  {
    slug: 'mint-julep',
    name: 'Mint Julep',
    description: 'A refreshing Florida classic showcasing Florida Bourbon with fresh mint and simple syrup.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-everglades-julep.webp',
    ingredients: ['2oz Florida Bourbon', '0.75oz Simple Syrup', 'Fresh Mint Leaves', 'Crushed Ice'],
    instructions: [
      'Muddle mint leaves and simple syrup in a julep cup or rocks glass.',
      'Add Florida Bourbon and fill with crushed ice, then stir until frost forms.',
      'Garnish with a mint sprig and serve with a straw.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Classic',
  },
  {
    slug: 'bourbon-gold-rush',
    name: 'Bourbon Gold Rush',
    description: 'A smooth Florida classic featuring Florida Bourbon with honey and lemon for a golden finish.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-gold-rush.webp',
    ingredients: ['2oz Florida Bourbon', '0.75oz Honey Syrup', '0.75oz Lemon Juice', 'Ice'],
    instructions: [
      'Fill a shaker with ice and add Florida Bourbon, honey syrup, and lemon juice.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with a lemon twist.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Sweet',
    category: 'Classic',
  },
  {
    slug: 'bourbon-high-roller',
    name: 'Bourbon High Roller',
    description: 'A sophisticated Florida cocktail featuring Florida Bourbon with ginger and citrus notes.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-high-roller.webp',
    ingredients: ['2oz Florida Bourbon', '0.5oz Ginger Liqueur', '0.75oz Lemon Juice', 'Ginger Beer'],
    instructions: [
      'Fill a highball glass with ice and add Florida Bourbon, ginger liqueur, and lemon juice.',
      'Top with ginger beer and stir gently.',
      'Garnish with a lemon wheel and candied ginger.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Spicy',
    category: 'Refreshing',
  },
  {
    slug: 'bourbon-kentucky-mule',
    name: 'Bourbon Kentucky Mule',
    description: 'A Florida twist on the Moscow mule featuring Florida Bourbon with ginger beer and lime.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-kentucky-mule.webp',
    ingredients: ['2oz Florida Bourbon', '0.5oz Lime Juice', 'Ginger Beer', 'Lime Wedge'],
    instructions: [
      'Fill a copper mug or highball glass with ice and add Florida Bourbon and lime juice.',
      'Top with ginger beer and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Spicy',
    category: 'Refreshing',
  },
  {
    slug: 'bourbon-midnight-miami',
    name: 'Bourbon Midnight Miami',
    description: 'A dark and mysterious Florida cocktail featuring Florida Bourbon with coffee liqueur and citrus.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-midnight-miami.webp',
    ingredients: ['2oz Florida Bourbon', '0.75oz Coffee Liqueur', '0.5oz Lemon Juice', 'Dash Angostura'],
    instructions: [
      'Fill a shaker with ice and add Florida Bourbon, coffee liqueur, lemon juice, and Angostura bitters.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a chilled coupe glass and garnish with an orange twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Rich',
    category: 'Sophisticated',
  },
  {
    slug: 'paper-plane',
    name: 'Paper Plane',
    description: 'A modern Florida classic featuring Florida Bourbon with Aperol, Amaro, and lemon.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-paper-plane.webp',
    ingredients: ['1oz Florida Bourbon', '1oz Aperol', '1oz Amaro', '1oz Lemon Juice'],
    instructions: [
      'Fill a shaker with ice and add Florida Bourbon, Aperol, Amaro, and lemon juice.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a coupe glass and garnish with a lemon twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bitter',
    category: 'Sophisticated',
  },
  {
    slug: 'bourbon-smash',
    name: 'Bourbon Smash',
    description: 'A refreshing Florida cocktail featuring Florida Bourbon muddled with fresh herbs and citrus.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-smash.webp',
    ingredients: ['2oz Florida Bourbon', '0.75oz Simple Syrup', 'Fresh Mint', 'Lemon Wedges'],
    instructions: [
      'Muddle mint leaves and lemon wedges with simple syrup in a shaker.',
      'Add Florida Bourbon and ice, then shake vigorously for 10 seconds.',
      'Strain into a rocks glass over fresh ice and garnish with mint sprigs.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'old-fashioned',
    name: 'Old Fashioned',
    description: 'A classic Florida old fashioned featuring smooth Florida Bourbon with sugar and bitters.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-smoked-old-fashioned.webp',
    ingredients: ['2oz Florida Bourbon', '0.25oz Simple Syrup', '2 Dashes Angostura Bitters', 'Orange Peel'],
    instructions: [
      'Add Florida Bourbon, simple syrup, and Angostura bitters to a rocks glass with a large ice cube.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Express orange peel over the drink, then garnish and serve.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bold',
    category: 'Classic',
  },
  {
    slug: 'whiskey-sour',
    name: 'Whiskey Sour',
    description: 'A classic Florida sour featuring Florida Bourbon with lemon and simple syrup.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-sunshine-sour.webp',
    ingredients: ['2oz Florida Bourbon', '0.75oz Lemon Juice', '0.75oz Simple Syrup', 'Egg White'],
    instructions: [
      'Add Florida Bourbon, lemon juice, simple syrup, and egg white to a shaker without ice.',
      'Dry shake vigorously for 15 seconds to emulsify the egg white.',
      'Add ice and shake again for 10 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with a lemon twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Classic',
  },
  {
    slug: 'manhattan',
    name: 'Manhattan',
    description: 'A sophisticated Florida classic featuring Florida Bourbon with sweet vermouth and bitters.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-paper-plane.webp',
    ingredients: ['2oz Florida Bourbon', '1oz Sweet Vermouth', '2 Dashes Angostura Bitters', 'Cherry'],
    instructions: [
      'Fill a mixing glass with ice and add Florida Bourbon, sweet vermouth, and Angostura bitters.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a chilled coupe glass.',
      'Garnish with a cherry and serve.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bold',
    category: 'Classic',
  },
  {
    slug: 'boulevardier',
    name: 'Boulevardier',
    description: 'A bold Florida cocktail featuring Florida Bourbon with Campari and sweet vermouth.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-midnight-miami.webp',
    ingredients: ['1.5oz Florida Bourbon', '1oz Campari', '1oz Sweet Vermouth', 'Orange Peel'],
    instructions: [
      'Fill a mixing glass with ice and add Florida Bourbon, Campari, and sweet vermouth.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice.',
      'Garnish with an orange twist and serve.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bitter',
    category: 'Sophisticated',
  },
  {
    slug: 'sazerac',
    name: 'Sazerac',
    description: 'A complex Florida classic featuring Florida Bourbon with absinthe, Peychaud\'s bitters, and sugar.',
    baseSpirit: 'bourbon',
    image: '/assets/cocktails/bourbon-gold-rush.webp',
    ingredients: ['2oz Florida Bourbon', '0.25oz Simple Syrup', '3 Dashes Peychaud\'s Bitters', 'Absinthe'],
    instructions: [
      'Rinse a chilled rocks glass with absinthe and discard excess.',
      'Add Florida Bourbon, simple syrup, and Peychaud\'s bitters to a mixing glass with ice.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into the prepared glass and garnish with a lemon twist.',
    ],
    difficulty: 'Advanced',
    prepTime: '5 mins',
    taste: 'Bold',
    category: 'Classic',
  },
  // Rum recipes
  {
    slug: 'daiquiri',
    name: 'Daiquiri',
    description: 'A classic Florida daiquiri featuring Ponce Rum with lime and simple syrup.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-1513-daiquiri.webp',
    ingredients: ['2oz Ponce Rum', '0.75oz Lime Juice', '0.75oz Simple Syrup', 'Ice'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, lime juice, and simple syrup.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a chilled coupe glass and garnish with a lime wheel.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Classic',
  },
  {
    slug: 'dark-n-stormy',
    name: 'Dark n Stormy',
    description: 'A tropical Florida classic featuring Ponce Rum with ginger beer and lime.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-dark-n-stormy.webp',
    ingredients: ['2oz Ponce Rum', '0.5oz Lime Juice', 'Ginger Beer', 'Lime Wedge'],
    instructions: [
      'Fill a highball glass with ice and add Ponce Rum and lime juice.',
      'Top with ginger beer and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Spicy',
    category: 'Tropical',
  },
  {
    slug: 'rum-fountain-youth',
    name: 'Rum Fountain of Youth',
    description: 'A refreshing Florida cocktail featuring Ponce Rum with tropical fruits and citrus.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-fountain-youth.webp',
    ingredients: ['2oz Ponce Rum', '1oz Pineapple Juice', '0.5oz Lime Juice', '0.5oz Simple Syrup'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, pineapple juice, lime juice, and simple syrup.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a highball glass over fresh ice and garnish with pineapple and lime.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Tropical',
  },
  {
    slug: 'rum-golden-galleon',
    name: 'Rum Golden Galleon',
    description: 'A rich Florida cocktail featuring Ponce Rum with honey and spices.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-golden-galleon.webp',
    ingredients: ['2oz Ponce Rum', '0.75oz Honey Syrup', '0.5oz Lemon Juice', 'Dash Allspice'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, honey syrup, lemon juice, and allspice.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with a lemon twist.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Sweet',
    category: 'Tropical',
  },
  {
    slug: 'mojito',
    name: 'Mojito',
    description: 'A refreshing Florida mojito featuring Ponce Rum with fresh mint and lime.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-governors-mojito.webp',
    ingredients: ['2oz Ponce Rum', '0.75oz Lime Juice', '0.75oz Simple Syrup', 'Fresh Mint'],
    instructions: [
      'Muddle mint leaves with lime juice and simple syrup in a highball glass.',
      'Add Ponce Rum and fill with ice, then top with club soda.',
      'Stir gently and garnish with mint sprigs and a lime wedge.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'rum-hot-buttered',
    name: 'Rum Hot Buttered',
    description: 'A warming Florida cocktail featuring Ponce Rum with butter, spices, and hot water.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-hot-buttered.webp',
    ingredients: ['2oz Ponce Rum', '1oz Butter', '0.5oz Brown Sugar', 'Hot Water'],
    instructions: [
      'Combine butter, brown sugar, and spices in a mug, then add Ponce Rum.',
      'Fill with hot water and stir until butter is melted.',
      'Garnish with a cinnamon stick and serve hot.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Rich',
    category: 'Classic',
  },
  {
    slug: 'rum-jungle-bird',
    name: 'Rum Jungle Bird',
    description: 'A tropical Florida cocktail featuring Ponce Rum with Campari, pineapple, and lime.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-jungle-bird.webp',
    ingredients: ['1.5oz Ponce Rum', '0.75oz Campari', '1.5oz Pineapple Juice', '0.5oz Lime Juice'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, Campari, pineapple juice, and lime juice.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with pineapple and a lime wheel.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bitter',
    category: 'Tropical',
  },
  {
    slug: 'planters-punch',
    name: 'Planters Punch',
    description: 'A classic tropical Florida punch featuring Ponce Rum with citrus and grenadine.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-planters-punch.webp',
    ingredients: ['2oz Ponce Rum', '1oz Orange Juice', '1oz Pineapple Juice', '0.5oz Grenadine'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, orange juice, pineapple juice, and grenadine.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a highball glass over fresh ice and garnish with fruit.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Tropical',
  },
  {
    slug: 'rum-runner-royale',
    name: 'Rum Runner Royale',
    description: 'A tropical Florida classic featuring Ponce Rum with blackberry and banana liqueurs.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-runner-royale.webp',
    ingredients: ['1.5oz Ponce Rum', '0.5oz Blackberry Liqueur', '0.5oz Banana Liqueur', '1oz Pineapple Juice'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, blackberry liqueur, banana liqueur, and pineapple juice.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a hurricane glass over fresh ice and garnish with fruit.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Tropical',
  },
  {
    slug: 'rum-st-augustine-sour',
    name: 'Rum St Augustine Sour',
    description: 'A Florida sour featuring Ponce Rum with lemon and simple syrup, named for Florida\'s oldest city.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-st-augustine-sour.webp',
    ingredients: ['2oz Ponce Rum', '0.75oz Lemon Juice', '0.75oz Simple Syrup', 'Egg White'],
    instructions: [
      'Add Ponce Rum, lemon juice, simple syrup, and egg white to a shaker without ice.',
      'Dry shake vigorously for 15 seconds, then add ice and shake again for 10 seconds.',
      'Strain into a rocks glass over fresh ice and garnish with a lemon twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Classic',
  },
  {
    slug: 'mai-tai',
    name: 'Mai Tai',
    description: 'A tropical Florida classic featuring Ponce Rum with orgeat, orange curaçao, and lime.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-jungle-bird.webp',
    ingredients: ['2oz Ponce Rum', '0.75oz Lime Juice', '0.5oz Orgeat', '0.5oz Orange Curaçao'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, lime juice, orgeat, and orange curaçao.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice.',
      'Garnish with a mint sprig and lime wheel.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Tropical',
  },
  {
    slug: 'pina-colada',
    name: 'Piña Colada',
    description: 'A creamy tropical Florida favorite featuring Ponce Rum with coconut and pineapple.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/keylime-colada.webp',
    ingredients: ['2oz Ponce Rum', '1oz Coconut Cream', '1oz Pineapple Juice', 'Ice'],
    instructions: [
      'Fill a blender with ice and add Ponce Rum, coconut cream, and pineapple juice.',
      'Blend until smooth and creamy.',
      'Pour into a hurricane glass and garnish with pineapple and a cherry.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Sweet',
    category: 'Tropical',
  },
  {
    slug: 'hurricane',
    name: 'Hurricane',
    description: 'A vibrant Florida classic featuring Ponce Rum with passion fruit and citrus.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-planters-punch.webp',
    ingredients: ['2oz Ponce Rum', '1oz Passion Fruit Syrup', '0.75oz Lemon Juice', '0.5oz Grenadine'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, passion fruit syrup, lemon juice, and grenadine.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a hurricane glass over fresh ice.',
      'Garnish with an orange slice and cherry.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Tropical',
  },
  {
    slug: 'zombie',
    name: 'Zombie',
    description: 'A powerful Florida tiki classic featuring Ponce Rum with multiple fruit juices and spices.',
    baseSpirit: 'rum',
    image: '/assets/cocktails/rum-runner-royale.webp',
    ingredients: ['1.5oz Ponce Rum', '1oz Pineapple Juice', '0.75oz Lime Juice', '0.5oz Falernum'],
    instructions: [
      'Fill a shaker with ice and add Ponce Rum, pineapple juice, lime juice, and falernum.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a zombie glass over fresh ice.',
      'Garnish with mint sprigs and fruit.',
    ],
    difficulty: 'Advanced',
    prepTime: '5 mins',
    taste: 'Bold',
    category: 'Tropical',
  },
  // Tequila recipes
  {
    slug: 'tequila-agave-old-fashioned',
    name: 'Tequila Agave Old Fashioned',
    description: 'A smooth Florida twist on the classic old fashioned featuring Tikaram Tequila with agave syrup.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-agave-old-fashioned.webp',
    ingredients: ['2oz Tikaram Tequila', '0.25oz Agave Syrup', '2 Dashes Angostura Bitters', 'Orange Peel'],
    instructions: [
      'Add Tikaram Tequila, agave syrup, and Angostura bitters to a rocks glass with a large ice cube.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Express orange peel over the drink, then garnish and serve.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bold',
    category: 'Classic',
  },
  {
    slug: 'batanga',
    name: 'Batanga',
    description: 'A simple Florida classic featuring Tikaram Tequila with cola and lime.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-batanga.webp',
    ingredients: ['2oz Tikaram Tequila', 'Cola', '0.5oz Lime Juice', 'Lime Wedge'],
    instructions: [
      'Fill a highball glass with ice and add Tikaram Tequila and lime juice.',
      'Top with cola and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Classic',
  },
  {
    slug: 'tequila-cucumber-cooler',
    name: 'Tequila Cucumber Cooler',
    description: 'A refreshing Florida cocktail featuring Tikaram Tequila with cucumber and lime.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-cucumber-cooler.webp',
    ingredients: ['2oz Tikaram Tequila', '0.75oz Lime Juice', '0.5oz Simple Syrup', 'Cucumber Slices'],
    instructions: [
      'Muddle cucumber slices with lime juice and simple syrup in a shaker.',
      'Add Tikaram Tequila and ice, then shake vigorously for 10 seconds.',
      'Strain into a highball glass over fresh ice and garnish with cucumber.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'tequila-el-diablo',
    name: 'Tequila El Diablo',
    description: 'A spicy Florida cocktail featuring Tikaram Tequila with crème de cassis and ginger beer.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-el-diablo.webp',
    ingredients: ['2oz Tikaram Tequila', '0.5oz Crème de Cassis', '0.5oz Lime Juice', 'Ginger Beer'],
    instructions: [
      'Fill a highball glass with ice and add Tikaram Tequila, crème de cassis, and lime juice.',
      'Top with ginger beer and stir gently.',
      'Garnish with a lime wheel and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Spicy',
    category: 'Refreshing',
  },
  {
    slug: 'tequila-jalapeno-ghost',
    name: 'Tequila Jalapeño Ghost',
    description: 'A spicy Florida cocktail featuring Tikaram Tequila with jalapeño and citrus.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-jalapeno-ghost.webp',
    ingredients: ['2oz Tikaram Tequila', '0.75oz Lime Juice', '0.5oz Simple Syrup', 'Jalapeño Slices'],
    instructions: [
      'Muddle jalapeño slices with lime juice and simple syrup in a shaker.',
      'Add Tikaram Tequila and ice, then shake vigorously for 10 seconds.',
      'Strain into a rocks glass over fresh ice and garnish with a jalapeño slice.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Spicy',
    category: 'Spicy',
  },
  {
    slug: 'paloma',
    name: 'Paloma',
    description: 'A refreshing Florida classic featuring Tikaram Tequila with grapefruit and lime.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-perfect-paloma.webp',
    ingredients: ['2oz Tikaram Tequila', '1oz Grapefruit Juice', '0.5oz Lime Juice', 'Club Soda'],
    instructions: [
      'Fill a highball glass with ice and add Tikaram Tequila, grapefruit juice, and lime juice.',
      'Top with club soda and stir gently.',
      'Garnish with a grapefruit wheel and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Classic',
  },
  {
    slug: 'ranch-water',
    name: 'Ranch Water',
    description: 'A simple Florida cocktail featuring Tikaram Tequila with lime and sparkling water.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-ranch-water.webp',
    ingredients: ['2oz Tikaram Tequila', '0.75oz Lime Juice', 'Sparkling Water', 'Lime Wedge'],
    instructions: [
      'Fill a highball glass with ice and add Tikaram Tequila and lime juice.',
      'Top with sparkling water and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'mexican-mule',
    name: 'Mexican Mule',
    description: 'A refreshing Florida mule featuring Tikaram Tequila with ginger beer and lime.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-el-diablo.webp',
    ingredients: ['2oz Tikaram Tequila', '0.5oz Lime Juice', 'Ginger Beer', 'Lime Wedge'],
    instructions: [
      'Fill a copper mug or highball glass with ice and add Tikaram Tequila and lime juice.',
      'Top with ginger beer and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Spicy',
    category: 'Refreshing',
  },
  {
    slug: 'tequila-siesta',
    name: 'Tequila Siesta',
    description: 'A refreshing Florida cocktail featuring Tikaram Tequila with Campari, grapefruit, and lime.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-siesta.webp',
    ingredients: ['1.5oz Tikaram Tequila', '0.75oz Campari', '0.75oz Grapefruit Juice', '0.5oz Lime Juice'],
    instructions: [
      'Fill a shaker with ice and add Tikaram Tequila, Campari, grapefruit juice, and lime juice.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with a grapefruit twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bitter',
    category: 'Sophisticated',
  },
  {
    slug: 'tequila-white-negrouni',
    name: 'Tequila White Negroni',
    description: 'A sophisticated Florida twist on the negroni featuring Tikaram Tequila with Suze and Lillet.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/tequila-white-negrouni.webp',
    ingredients: ['1oz Tikaram Tequila', '1oz Suze', '1oz Lillet Blanc', 'Orange Peel'],
    instructions: [
      'Fill a mixing glass with ice and add Tikaram Tequila, Suze, and Lillet Blanc.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with an orange twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bitter',
    category: 'Sophisticated',
  },
  // Key Lime Tequila recipes
  {
    slug: 'keylime-colada',
    name: 'Key Lime Colada',
    description: 'A tropical Florida twist on the piña colada featuring Key Lime Tequila with coconut and pineapple.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-colada.webp',
    ingredients: ['2oz Key Lime Tequila', '1oz Coconut Cream', '1oz Pineapple Juice', '0.5oz Lime Juice'],
    instructions: [
      'Fill a blender with ice and add Key Lime Tequila, coconut cream, pineapple juice, and lime juice.',
      'Blend until smooth and creamy.',
      'Pour into a hurricane glass and garnish with pineapple and a lime wheel.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Tropical',
  },
  {
    slug: 'keylime-fizz',
    name: 'Key Lime Fizz',
    description: 'A refreshing Florida fizz featuring Key Lime Tequila with citrus and sparkling water.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-fizz.webp',
    ingredients: ['2oz Key Lime Tequila', '0.75oz Lime Juice', '0.5oz Simple Syrup', 'Club Soda'],
    instructions: [
      'Fill a highball glass with ice and add Key Lime Tequila, lime juice, and simple syrup.',
      'Top with club soda and stir gently.',
      'Garnish with a lime wheel and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'keylime-gimlet',
    name: 'Key Lime Gimlet',
    description: 'A classic Florida gimlet featuring Key Lime Tequila with lime cordial.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-gimlet.webp',
    ingredients: ['2oz Key Lime Tequila', '0.75oz Lime Cordial', 'Ice'],
    instructions: [
      'Fill a shaker with ice and add Key Lime Tequila and lime cordial.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a chilled coupe glass and garnish with a lime wheel.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Classic',
  },
  {
    slug: 'margarita',
    name: 'Margarita',
    description: 'A Florida classic featuring Tikaram Tequila with triple sec and fresh lime.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-margarita.webp',
    ingredients: ['2oz Tikaram Tequila', '1oz Triple Sec', '0.75oz Lime Juice', 'Salt Rim'],
    instructions: [
      'Rim a margarita glass with salt, then fill a shaker with ice.',
      'Add Tikaram Tequila, triple sec, and lime juice, then shake vigorously for 10-15 seconds.',
      'Strain into the prepared glass and garnish with a lime wheel.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Classic',
  },
  {
    slug: 'keylime-mojito-twist',
    name: 'Key Lime Mojito Twist',
    description: 'A refreshing Florida twist on the mojito featuring Key Lime Tequila with fresh mint.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-mojito-twist.webp',
    ingredients: ['2oz Key Lime Tequila', '0.75oz Lime Juice', '0.75oz Simple Syrup', 'Fresh Mint'],
    instructions: [
      'Muddle mint leaves with lime juice and simple syrup in a highball glass.',
      'Add Key Lime Tequila and fill with ice, then top with club soda.',
      'Stir gently and garnish with mint sprigs and a lime wedge.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'keylime-pie-martini',
    name: 'Key Lime Pie Martini',
    description: 'A decadent Florida dessert cocktail featuring Key Lime Tequila with vanilla and cream.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-pie-martini.webp',
    ingredients: ['2oz Key Lime Tequila', '1oz Vanilla Liqueur', '0.5oz Lime Juice', 'Heavy Cream'],
    instructions: [
      'Fill a shaker with ice and add Key Lime Tequila, vanilla liqueur, lime juice, and heavy cream.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a chilled martini glass and garnish with graham cracker crumbs.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Sophisticated',
  },
  {
    slug: 'keylime-rickey',
    name: 'Key Lime Rickey',
    description: 'A simple Florida cocktail featuring Key Lime Tequila with lime and sparkling water.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-rickey.webp',
    ingredients: ['2oz Key Lime Tequila', '0.75oz Lime Juice', 'Sparkling Water', 'Lime Wedge'],
    instructions: [
      'Fill a highball glass with ice and add Key Lime Tequila and lime juice.',
      'Top with sparkling water and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'keylime-smash',
    name: 'Key Lime Smash',
    description: 'A refreshing Florida smash featuring Key Lime Tequila muddled with fresh herbs and citrus.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-smash.webp',
    ingredients: ['2oz Key Lime Tequila', '0.75oz Simple Syrup', 'Fresh Mint', 'Lime Wedges'],
    instructions: [
      'Muddle mint leaves and lime wedges with simple syrup in a shaker.',
      'Add Key Lime Tequila and ice, then shake vigorously for 10 seconds.',
      'Strain into a rocks glass over fresh ice and garnish with mint sprigs.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'keylime-spicy-sour',
    name: 'Key Lime Spicy Sour',
    description: 'A bold Florida sour featuring Key Lime Tequila with jalapeño and citrus.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-spicy-sour.webp',
    ingredients: ['2oz Key Lime Tequila', '0.75oz Lime Juice', '0.5oz Simple Syrup', 'Jalapeño Slices'],
    instructions: [
      'Muddle jalapeño slices with lime juice and simple syrup in a shaker.',
      'Add Key Lime Tequila and ice, then shake vigorously for 10 seconds.',
      'Strain into a rocks glass over fresh ice and garnish with a jalapeño slice.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Spicy',
    category: 'Spicy',
  },
  {
    slug: 'keylime-sunrise-twist',
    name: 'Key Lime Sunrise Twist',
    description: 'A vibrant Florida twist on the sunrise featuring Key Lime Tequila with orange and grenadine.',
    baseSpirit: 'tequila',
    image: '/assets/cocktails/keylime-sunrise-twist.webp',
    ingredients: ['2oz Key Lime Tequila', 'Orange Juice', 'Grenadine', 'Lime Wheel'],
    instructions: [
      'Fill a highball glass with ice and add Key Lime Tequila.',
      'Top with orange juice, leaving about an inch at the top, then slowly pour grenadine over the back of a spoon.',
      'Garnish with a lime wheel and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Sweet',
    category: 'Classic',
  },
  // Paan Liqueur recipes
  {
    slug: 'paan-after-dinner',
    name: 'Paan After Dinner',
    description: 'A sophisticated Florida digestif featuring Paan Liqueur with coffee and cream.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-after-dinner.webp',
    ingredients: ['1.5oz Paan Liqueur', '0.5oz Coffee Liqueur', '0.5oz Heavy Cream', 'Ice'],
    instructions: [
      'Fill a mixing glass with ice and add Paan Liqueur, coffee liqueur, and heavy cream.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a chilled coupe glass and garnish with coffee beans.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Rich',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-botanist',
    name: 'Paan Botanist',
    description: 'A floral Florida cocktail featuring Paan Liqueur with gin and botanical notes.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-botanist.webp',
    ingredients: ['1.5oz Paan Liqueur', '1oz Gin', '0.5oz Lemon Juice', 'Elderflower Tonic'],
    instructions: [
      'Fill a highball glass with ice and add Paan Liqueur, gin, and lemon juice.',
      'Top with elderflower tonic and stir gently.',
      'Garnish with rose petals and serve.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Refreshing',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-calcutta-cup',
    name: 'Paan Calcutta Cup',
    description: 'A refreshing Florida cocktail featuring Paan Liqueur with citrus and sparkling water.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-calcutta-cup.webp',
    ingredients: ['2oz Paan Liqueur', '0.75oz Lime Juice', 'Club Soda', 'Mint Leaves'],
    instructions: [
      'Fill a highball glass with ice and add Paan Liqueur and lime juice.',
      'Top with club soda and stir gently.',
      'Garnish with mint leaves and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'paan-crimson-velvet',
    name: 'Paan Crimson Velvet',
    description: 'A rich Florida cocktail featuring Paan Liqueur with red wine and spices.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-crimson-velvet.webp',
    ingredients: ['1.5oz Paan Liqueur', '2oz Red Wine', '0.5oz Simple Syrup', 'Cinnamon Stick'],
    instructions: [
      'Fill a wine glass with ice and add Paan Liqueur, red wine, and simple syrup.',
      'Stir gently to combine.',
      'Garnish with a cinnamon stick and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Rich',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-midnight-mumbai',
    name: 'Paan Midnight Mumbai',
    description: 'A dark and exotic Florida cocktail featuring Paan Liqueur with coffee and spices.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-midnight-mumbai.webp',
    ingredients: ['1.5oz Paan Liqueur', '0.75oz Coffee Liqueur', '0.5oz Lemon Juice', 'Dash Angostura'],
    instructions: [
      'Fill a shaker with ice and add Paan Liqueur, coffee liqueur, lemon juice, and Angostura bitters.',
      'Shake vigorously for 10-15 seconds until well-chilled.',
      'Strain into a chilled coupe glass and garnish with an orange twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Rich',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-negroni',
    name: 'Paan Negroni',
    description: 'An exotic Florida twist on the classic negroni featuring Paan Liqueur with gin and Campari.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-negroni.webp',
    ingredients: ['1oz Paan Liqueur', '1oz Gin', '1oz Campari', 'Orange Peel'],
    instructions: [
      'Fill a mixing glass with ice and add Paan Liqueur, gin, and Campari.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a rocks glass over fresh ice and garnish with an orange twist.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bitter',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-rose-lassi',
    name: 'Paan Rose Lassi',
    description: 'A creamy Florida cocktail featuring Paan Liqueur with rose water and yogurt.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-rose-lassi.webp',
    ingredients: ['2oz Paan Liqueur', '1oz Rose Water', '2oz Yogurt', '0.5oz Simple Syrup'],
    instructions: [
      'Combine Paan Liqueur, rose water, yogurt, and simple syrup in a shaker.',
      'Shake vigorously for 10-15 seconds until well-combined.',
      'Strain into a highball glass over fresh ice and garnish with rose petals.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Sweet',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-royal-martini',
    name: 'Paan Royal Martini',
    description: 'A sophisticated Florida martini featuring Paan Liqueur with gin and vermouth.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-royal-martini.webp',
    ingredients: ['1.5oz Paan Liqueur', '1oz Gin', '0.5oz Dry Vermouth', 'Rose Petal'],
    instructions: [
      'Fill a mixing glass with ice and add Paan Liqueur, gin, and dry vermouth.',
      'Stir gently for 20-30 seconds until well-chilled.',
      'Strain into a chilled martini glass and garnish with a rose petal.',
    ],
    difficulty: 'Medium',
    prepTime: '5 mins',
    taste: 'Bold',
    category: 'Sophisticated',
  },
  {
    slug: 'paan-tonic',
    name: 'Paan Tonic',
    description: 'A refreshing Florida cocktail featuring Paan Liqueur with tonic water and citrus.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-ruby-tonic.webp',
    ingredients: ['2oz Paan Liqueur', '0.5oz Lime Juice', 'Tonic Water', 'Lime Wedge'],
    instructions: [
      'Fill a highball glass with ice and add Paan Liqueur and lime juice.',
      'Top with tonic water and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
  {
    slug: 'paan-spiced-mule',
    name: 'Paan Spiced Mule',
    description: 'A spicy Florida mule featuring Paan Liqueur with ginger beer and lime.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-spiced-mule.webp',
    ingredients: ['2oz Paan Liqueur', '0.5oz Lime Juice', 'Ginger Beer', 'Lime Wedge'],
    instructions: [
      'Fill a highball glass with ice and add Paan Liqueur and lime juice.',
      'Top with ginger beer and stir gently.',
      'Garnish with a lime wedge and serve.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Spicy',
    category: 'Refreshing',
  },
  {
    slug: 'paan-spritz',
    name: 'Paan Spritz',
    description: 'A light and refreshing Florida spritz featuring Paan Liqueur with prosecco and soda water.',
    baseSpirit: 'liqueur',
    image: '/assets/cocktails/paan-ruby-tonic.webp',
    ingredients: ['1.5oz Paan Liqueur', '3oz Prosecco', '1oz Soda Water', 'Orange Slice'],
    instructions: [
      'Fill a wine glass with ice and add Paan Liqueur.',
      'Top with prosecco and soda water.',
      'Stir gently and garnish with an orange slice.',
    ],
    difficulty: 'Easy',
    prepTime: '3 mins',
    taste: 'Refreshing',
    category: 'Refreshing',
  },
]

export function getRecipesBySpirit(spirit: string): Recipe[] {
  return recipes.filter((recipe) => recipe.baseSpirit === spirit.toLowerCase())
}

// Map product categories to recipe baseSpirit values
function mapCategoryToBaseSpirit(category: string): string {
  const mapping: Record<string, string> = {
    Rum: 'rum',
    Bourbon: 'bourbon',
    Tequila: 'tequila',
    Liqueur: 'liqueur',
  }
  return mapping[category] || category.toLowerCase()
}

export function getRecipesByProductCategory(category: string): Recipe[] {
  const baseSpirit = mapCategoryToBaseSpirit(category)
  return recipes.filter((recipe) => recipe.baseSpirit === baseSpirit)
}

