// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      leads: {
        Row: {
          id: string
          email: string
          first_name: string | null
          is_verified: boolean
          coupon_code: string | null
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          first_name?: string | null
          is_verified?: boolean
          coupon_code?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          first_name?: string | null
          is_verified?: boolean
          coupon_code?: string | null
          created_at?: string
        }
      }
      stores: {
        Row: {
          id: string
          name: string
          address_line1: string
          city: string
          state: string
          zip_code: string
          lat: number
          lng: number
          phone: string | null
        }
        Insert: {
          id?: string
          name: string
          address_line1: string
          city: string
          state: string
          zip_code: string
          lat: number
          lng: number
          phone?: string | null
        }
        Update: {
          id?: string
          name?: string
          address_line1?: string
          city?: string
          state?: string
          zip_code?: string
          lat?: number
          lng?: number
          phone?: string | null
        }
      }
      products: {
        Row: {
          slug: string
          name: string
          category: string | null
          abv: string | null
          tasting_notes: Json | null
        }
        Insert: {
          slug: string
          name: string
          category?: string | null
          abv?: string | null
          tasting_notes?: Json | null
        }
        Update: {
          slug?: string
          name?: string
          category?: string | null
          abv?: string | null
          tasting_notes?: Json | null
        }
      }
    }
  }
}

